name: ascot-osx
channels:
  - conda-forge
dependencies:
  - c-compiler
  - make
  - glib
  - python>=3.10
  - hdf5
  - zlib
  - setuptools
  - pip
  - ipython
  - numpy
  - scipy
  - desc-opt
  - netCDF4
  - h5py
  - xmlschema
  - unyt
  - wurlitzer
  - matplotlib
  - pyvista
  - freeqdsk
  - doxygen
  - ruff
  - ipykernel
  - pandoc
  - sphinx==6.*
  - numpydoc
  - nbsphinx
  - nbformat
  - breathe
  - sphinxcontrib-bibtex
  - sphinx-rtd-theme
  - sphinx-gallery
  - sphinx-design
  - sphinxcontrib-mermaid
  - clang==17.*
  - clang-tools==17*
  - libclang==17.*
  - llvm-openmp==17.*
  - pylint
  - pip:
    - libclang==17.*
    # PR branch for macos + clang-16+ support
    - ctypeslib2 @ git+https://github.com/dgarnier/ctypeslib.git@anon_union_macos
