name: ascot-env
channels:
  - conda-forge
dependencies:
  - c-compiler
  - llvm-openmp
  - python>=3.12
  - make
  - pip
  - numpy>=2.0
  - unyt
  - scipy
  - h5py
  - tomli_w
  - xmlschema
  - ipython
  - matplotlib
  - pyvista
