name: ascot-dev
channels:
  - conda-forge
dependencies:
  - c-compiler
  - make
  - glib
  - llvm-openmp
  - python>=3.10
  - hdf5=*=*openmp*
  - mpi=*=*openmp*
  - zlib
  - setuptools
  - pip
  - ipython
  - numpy
  - scipy
  - h5py
  - mpi4py
  - xmlschema
  - unyt
  - wurlitzer
  - matplotlib
  - pyvista
  - freeqdsk
  - doxygen
  - ruff
  - ipykernel
  - pandoc
  - sphinx==6.*
  - numpydoc
  - nbsphinx
  - nbformat
  - breathe
  - sphinxcontrib-bibtex
  - sphinx-rtd-theme
  - sphinx-gallery
  - sphinx-design
  - sphinxcontrib-mermaid
  - clang==15.*
  - clang-tools==15.*
  - libclang==15.*
  - llvm-openmp==15.*
  - libsanitizer
  - pylint
  - pip:
    - clang==15.*
    - ctypeslib2
    - desc-opt
    - netCDF4	
