name: ascot-dev
channels:
  - conda-forge
dependencies:
  - c-compiler
  - llvm-openmp
  - python>=3.12
  - make
  - pip
  - numpy>=2.0
  - unyt
  - scipy
  - h5py
  - xmlschema
  - ipython
  - matplotlib
  - pyvista
  - ipykernel
  - pandoc
  - sphinx==6.*
  - numpydoc
  - nbsphinx
  - nbformat
  - sphinxcontrib-bibtex
  - sphinx-rtd-theme
  - sphinx-gallery
  - sphinx-design
  - doxygen
  - libsanitizer
  - pylint
  - mypy
  - pytest