/**
 * @file diag.h
 * Interface for simulation diagnostics.
 *
 * Ascot standard output consists of inistate and endstate. Any other output is
 * generated by "diagnostics" that are updated during the simulation. All
 * diagnostics are accessed via this interface. To implement a new diagnostics,
 * it is enough that one add calls to that diagnostics routines here.
 *
 * One limitation for diagnostic data is that the size of the data must be known
 * before simulation begins so that offloading of that data is possible.
 */
#ifndef DIAG_H
#define DIAG_H
#include "bfield.h"
#include "defines.h"
#include "options.h"
#include "marker.h"
#include "diag_data.h"

/**
 * @brief Free allocated resources
 *
 * @param data diagnostics data
 */
void diag_free(Diagnostics *diag, Options *params);

/**
 * @brief Offload data to the accelerator.
 *
 * @param data pointer to the data struct
 */
void diag_offload(Diagnostics *diag, Options *params);

/**
 * @brief Collects diagnostics when marker represents a particle
 *
 * @param data diagnostics data struct
 * @param Bdata pointer to magnetic field data
 * @param p_f pointer to SIMD struct storing marker states at the end of current
 *        time-step
 * @param p_i pointer to SIMD struct storing marker states at the beginning of
 *        current time-step
 */
void diag_update_go(
    Diagnostics *diag, Options *params, Bfield *bfield,
    MarkerGyroOrbit *p_f, MarkerGyroOrbit *p_i);

/**
 * @brief Collects diagnostics when marker represents a guiding center
 *
 * @param data pointer to diagnostics data struct
 * @param Bdata pointer to magnetic field data
 * @param p_f pointer to SIMD struct storing marker states at the end of current
 *        time-step
 * @param p_i pointer to SIMD struct storing marker states at the beginning of
 *        current time-step
 */
void diag_update_gc(
    Diagnostics *diag, Options *params, Bfield *bfield,
    MarkerGuidingCenter *p_f, MarkerGuidingCenter *p_i);

/**
 * @brief Collects diagnostics when marker represents a magnetic field line
 *
 * Distributions are not updated for magnetic field lines.
 *
 * @param data pointer to diagnostics data struct
 * @param p_f pointer to SIMD struct storing marker states at the end of current
 *        time-step
 * @param p_i pointer to SIMD struct storing marker states at the beginning of
 *        current time-step
 */
void diag_update_fl(
    Diagnostics *diag, Options *params, MarkerFieldLine *p_f,
    MarkerFieldLine *p_i);

#endif
