name: (Reusable) Build
on: [workflow_call]

jobs:

  Build-Code:
    if: always() || failure()
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.10"
          environment-file: environment-dev.yaml
          activate-environment: ascot-dev
          auto-activate-base: false

      - name: Make ascot5_main with MPI
        run: |
          make ascot5_main MPI=1 -j

      - name: Make clean
        run: make clean

      - name: Make ascot5_main without MPI
        run: make ascot5_main -j

      - name: Make libascot.so
        run: make libascot

      - name: Make BBNBI
        run: make bbnbi5

      - name: Make ascot2py
        run: make ascot2py.py

      - name: Set permissions and pack
        run: |
          cd ./build
          chmod +x ascot5_main bbnbi5
          tar -cf code.tar ascot5_main bbnbi5 libascot.so
          cd ..

      - name: Upload code
        uses: actions/upload-artifact@main
        with:
          name: code
          path: ./build/code.tar

      - name: Upload ascot2py.py
        uses: actions/upload-artifact@main
        with:
          name: ascot2py
          path: ./a5py/ascotpy/ascot2py.py
