name: Compile
on: [push, workflow_dispatch]

jobs:
  compile-all:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ascot4fusion/ascot5deps:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4

      - name: Make ascot5_main with MPI
        run: make ascot5_main MPI=1 FLAGS="-foffload=disable"

      - name: Make clean
        run: make clean

      - name: Make ascot5_main without MPI
        run: make ascot5_main MPI=0 FLAGS="-foffload=disable"

      - name: Make libascot.so
        run: make libascot MPI=0 FLAGS="-foffload=disable"

      - name: Make BBNBI
        run: make bbnbi5 MPI=0 FLAGS="-foffload=disable"

      - name: Make ascot2py
        run: make ascot2py.py MPI=0 FLAGS="-foffload=disable"

      - name: Upload ascot5_main as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ascot5_main
          path: ./build/ascot5_main

      - name: Upload libascot.so as artifact
        uses: actions/upload-artifact@v3
        with:
          name: libascot.so
          path: ./build/libascot.so

      - name: Upload ascot2py.py as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: ascot2py.py
          path: ./a5py/ascotpy/ascot2py.py

      - name: Upload bbnbi as artifact
        uses: actions/upload-artifact@v3
        with:
          name: bbnbi
          path: ./build/bbnbi5
