name: Docs
on: [workflow_dispatch]
permissions:
    contents: write
jobs:
  compile:
    runs-on: ubuntu-latest
    name: Compile ascot5
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned."

      - name: Make ascot5_main
        uses: ./.github/actions/compile/
        id: makeascot5main
        with:
          makefile-parameters: 'ascot5_main MPI=0 FLAGS="-foffload=disable"'

      - name: Make libascot.so
        uses: ./.github/actions/compile/
        id: makelibascot
        with:
          makefile-parameters: 'libascot MPI=0 FLAGS="-foffload=disable"'

      - name: Upload ascot5_main as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ascot5_main
          path: ./build/ascot5_main

      - name: Upload libascot.so as artifact
        uses: actions/upload-artifact@v3
        with:
          name: libascot.so
          path: ./build/libascot.so

  build:
    needs: compile
    runs-on: ubuntu-latest
    steps:
      # Checkout most recent version of this branch on ascot5 repo
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      # Packages required to compile documentation, got pandoc working this way
      - name: Install dependencies
        run: |
          sudo apt-get install -y libhdf5-dev
          sudo apt-get install -y doxygen
          sudo apt install pandoc
          pip install -e .[doc]
          pip uninstall vtk -y
          pip install vtk-osmesa --extra-index-url https://wheels.vtk.org
      - uses: actions/download-artifact@v3
        with:
          name: ascot5_main
          path: ./build/
      - run: chmod +x ./build/ascot5_main
      - uses: actions/download-artifact@v3
        with:
          name: libascot.so
          path: ./build/
      - name: Run tutorials
        working-directory: ./a5py/testascot/
        run: |
          python tutorials.py
      # Figures repo is stored as a subfolder since otherwise it would clean
      # ascot5 repo. The SSH key corresponds to deploy key in figures repo.
      - name: Clone figures repository
        uses: actions/checkout@master
        with:
          repository: ascot4fusion/figures
          ssh-key: ${{ secrets.SSH_KEY_FIGURES }}
          path: figures
      - name: Sphinx build
        run: |
          make doc
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./build/doc

  publish:
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    # Change the ref to refs/heads/main once the code is merged
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/feature/8-merging-python-and-c-repositories' }}
    steps:
      - name: Publish
        id: deployment
        uses: actions/deploy-pages@v2
