name: Docs
on: [push, pull_request, workflow_dispatch]
permissions:
    contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout most recent version of this branch on ascot5 repo
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      # Packages required to compile documentation, got pandoc working this way
      - name: Install dependencies
        run: |
          sudo apt-get install -y doxygen
          sudo apt install pandoc
          pip install -e .[doc]
      # Figures repo is stored as a subfolder since otherwise it would clean
      # ascot5 repo. The SSH key corresponds to deploy key in figures repo.
      - name: Clone figures repository
        uses: actions/checkout@master
        with:
          repository: ascot4fusion/figures
          ssh-key: ${{ secrets.SSH_KEY_FIGURES }}
          path: figures
      - name: Sphinx build
        run: |
          make doc
          ls
          ls build
          ls build/doc
          ls ..
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: |
            "./build/doc"
            "./figures"

  publish:
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    # Change the ref to refs/heads/main once the code is merged
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/feature/8-merging-python-and-c-repositories' }}
    steps:
      - name: Publish
        id: deployment
        uses: actions/deploy-pages@v2
