name: Docs
on: [push, pull_request, workflow_dispatch]
permissions:
    contents: write
jobs:
  docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          sudo apt-get install -y doxygen
          sudo apt install pandoc
          pip install -e .[doc]
      - name: Clone figures repository
        uses: actions/checkout@master
        with:
          repository: ascot4fusion/figures
          path: figures
      - name: Sphinx build
        run: |
          pwd
          ls
          ls figures
          make doc
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # Change the ref to refs/heads/main once the code is merged
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/feature/8-merging-python-and-c-repositories' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/doc/
          force_orphan: true
