name: Mirror to GitLab

on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Mirror repository
        env:
          GITLAB_USERNAME: ${{ secrets.EUFUSGITLAB_USERNAME }}
          GITLAB_TOKEN: ${{ secrets.EUFUSGITLAB_TOKEN }}
        run: |
          git clone --mirror "$GITHUB_SERVER_URL/${GITHUB_REPOSITORY}.git" repo.git
          cd repo.git

          git push --mirror \
            "https://${GITLAB_USERNAME}:${GITLAB_TOKEN}@gitlab.eufus.psnc.pl/g2ksarki/ascot5.git"